// =============================================================================
// REAL MUGSHOTS SEED — paired real (person, county, state, charge) tuples
// with working mugshot URLs from the Supabase `mugshots` public bucket.
// =============================================================================
// Generated by scripts/pull-real-seed.js at session time. The pairing between
// person and mugshot is DEMO-ONLY — the scraper stores mugshots by content-hash
// with no link back to the record, so we pair randomly for visual realism.
// Persons, counties, states and charges are real from `enriched_records`.
// =============================================================================

import seed from './realDemoSeed.json';
import { canonicalSvgFipsFor } from '../utils/canonicalFips';

interface RawSeedEntry {
    personName: string;
    sex: string | null;
    race: string | null;
    age: number | null;
    county: string;
    state: string;
    bookingDate: string | null;
    topCharge: string | null;
    chargeCount: number;
    mugshotUrl: string;
}

export interface RealMugshotEntry {
    personId: string;
    displayName: string;
    dobYear: number;
    jurisdictionId: string; // canonical SVG FIPS (e.g. 'c42043' for Dauphin PA)
    countyDisplayName: string; // e.g. "Dauphin County"
    stateCode: string;
    topCharge: string | null;
    mugshotUrl: string;
}

function titleCase(name: string): string {
    return name.toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase());
}

// Pre-process into the shape the demo roster uses. Drop entries whose
// (state, county) can't be resolved against canonical US Census FIPS.
export const REAL_MUGSHOT_ENTRIES: RealMugshotEntry[] = (() => {
    const entries: RealMugshotEntry[] = [];
    const rawEntries = (seed as { entries: RawSeedEntry[] }).entries;
    let idCounter = 1;
    for (const raw of rawEntries) {
        const svgFips = canonicalSvgFipsFor(raw.state, raw.county);
        if (!svgFips) continue; // skip unresolvable
        const age = raw.age ?? 35;
        const bookingYear = raw.bookingDate ? new Date(raw.bookingDate).getFullYear() : 2026;
        entries.push({
            personId: `REAL-${String(idCounter++).padStart(4, '0')}`,
            displayName: titleCase(raw.personName),
            dobYear: bookingYear - age,
            jurisdictionId: svgFips,
            countyDisplayName: `${raw.county} County`,
            stateCode: raw.state,
            topCharge: raw.topCharge,
            mugshotUrl: raw.mugshotUrl,
        });
    }
    return entries;
})();

// Unique jurisdictions these real entries cover (so we can merge into DEMO_JURISDICTIONS).
export const REAL_MUGSHOT_JURISDICTIONS = (() => {
    const seen = new Map<string, { jurisdictionId: string; displayName: string; stateCode: string; stateName: string }>();
    const stateNames: Record<string, string> = {
        CA: 'California', TX: 'Texas', FL: 'Florida', NY: 'New York', IL: 'Illinois',
        PA: 'Pennsylvania', OH: 'Ohio', GA: 'Georgia', NC: 'North Carolina', AZ: 'Arizona',
        WA: 'Washington', MI: 'Michigan', MA: 'Massachusetts', CO: 'Colorado',
        TN: 'Tennessee', KY: 'Kentucky', MT: 'Montana', WY: 'Wyoming', NV: 'Nevada',
        AL: 'Alabama', AR: 'Arkansas', SC: 'South Carolina', UT: 'Utah', OR: 'Oregon',
        IN: 'Indiana', MO: 'Missouri', LA: 'Louisiana', MN: 'Minnesota', WI: 'Wisconsin',
        MD: 'Maryland', VA: 'Virginia', NJ: 'New Jersey', OK: 'Oklahoma', NM: 'New Mexico',
        KS: 'Kansas', MS: 'Mississippi', IA: 'Iowa', ND: 'North Dakota', SD: 'South Dakota',
        NE: 'Nebraska', WV: 'West Virginia', VT: 'Vermont', NH: 'New Hampshire', ID: 'Idaho',
        ME: 'Maine', RI: 'Rhode Island', CT: 'Connecticut', DE: 'Delaware', AK: 'Alaska',
        HI: 'Hawaii', DC: 'District of Columbia',
    };
    for (const e of REAL_MUGSHOT_ENTRIES) {
        if (!seen.has(e.jurisdictionId)) {
            seen.set(e.jurisdictionId, {
                jurisdictionId: e.jurisdictionId,
                displayName: e.countyDisplayName,
                stateCode: e.stateCode,
                stateName: stateNames[e.stateCode] || e.stateCode,
            });
        }
    }
    return Array.from(seen.values());
})();
