// =============================================================================
// REAL MUGSHOTS SEED — 100 paired real records from live Supabase
// =============================================================================
// 100 real (person, county, state, charges, demographics) tuples paired with
// 100 random-sample mugshot URLs from the public Supabase `mugshots` bucket.
// Regenerated by scripts/pull-big-seed.js against the live DB. Person rows
// are real from `enriched_records` including full demographics. The (person,
// mugshot) pairing is demo-only — the scraper stores mugshots by content-hash
// with no link back to the record.
// =============================================================================

import seed from './realDemoSeed.json';
import { canonicalSvgFipsFor } from '../utils/canonicalFips';

interface RawSeedEntry {
    personName: string;
    sex: string | null;
    race: string | null;
    age: number | null;
    dob: string | null;
    heightInches: number | null;
    weightLbs: number | null;
    hairColor: string | null;
    eyeColor: string | null;
    bondTotal: number | null;
    caseNumber: string | null;
    county: string;
    state: string;
    bookingDate: string | null;
    bookingDatetimeText: string | null;
    topCharge: string | null;
    allCharges: string[];
    chargeCount: number;
    mugshotUrl: string;
}

export interface RealMugshotEntry {
    personId: string;
    displayName: string;
    dobYear: number;
    jurisdictionId: string;
    countyDisplayName: string;
    stateCode: string;
    // Full demographics when available
    sex: string | null;
    race: string | null;
    age: number | null;
    heightInches: number | null;
    weightLbs: number | null;
    hairColor: string | null;
    eyeColor: string | null;
    bondTotal: number | null;
    caseNumber: string | null;
    bookingDate: string | null;
    topCharge: string | null;
    allCharges: string[];
    mugshotUrl: string;
}

function titleCase(name: string): string {
    return name.toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase());
}

export const REAL_MUGSHOT_ENTRIES: RealMugshotEntry[] = (() => {
    const entries: RealMugshotEntry[] = [];
    const rawEntries = (seed as { entries: RawSeedEntry[] }).entries;
    let idCounter = 1;
    for (const raw of rawEntries) {
        const svgFips = canonicalSvgFipsFor(raw.state, raw.county);
        if (!svgFips) continue;
        const age = raw.age ?? 35;
        const bookingYear = raw.bookingDate ? new Date(raw.bookingDate).getFullYear() : 2026;
        entries.push({
            personId: `REAL-${String(idCounter++).padStart(4, '0')}`,
            displayName: titleCase(raw.personName),
            dobYear: bookingYear - age,
            jurisdictionId: svgFips,
            countyDisplayName: `${raw.county} County`,
            stateCode: raw.state,
            sex: raw.sex,
            race: raw.race,
            age: raw.age,
            heightInches: raw.heightInches,
            weightLbs: raw.weightLbs,
            hairColor: raw.hairColor,
            eyeColor: raw.eyeColor,
            bondTotal: raw.bondTotal,
            caseNumber: raw.caseNumber,
            bookingDate: raw.bookingDate,
            topCharge: raw.topCharge,
            allCharges: raw.allCharges || [],
            mugshotUrl: raw.mugshotUrl,
        });
    }
    return entries;
})();

/** Jurisdictions covered by real-mugshot entries (for merging into DEMO_JURISDICTIONS) */
export const REAL_MUGSHOT_JURISDICTIONS = (() => {
    const seen = new Map<string, { jurisdictionId: string; displayName: string; stateCode: string; stateName: string }>();
    const stateNames: Record<string, string> = {
        CA: 'California', TX: 'Texas', FL: 'Florida', NY: 'New York', IL: 'Illinois',
        PA: 'Pennsylvania', OH: 'Ohio', GA: 'Georgia', NC: 'North Carolina', AZ: 'Arizona',
        WA: 'Washington', MI: 'Michigan', MA: 'Massachusetts', CO: 'Colorado',
        TN: 'Tennessee', KY: 'Kentucky', MT: 'Montana', WY: 'Wyoming', NV: 'Nevada',
        AL: 'Alabama', AR: 'Arkansas', SC: 'South Carolina', UT: 'Utah', OR: 'Oregon',
        IN: 'Indiana', MO: 'Missouri', LA: 'Louisiana', MN: 'Minnesota', WI: 'Wisconsin',
        MD: 'Maryland', VA: 'Virginia', NJ: 'New Jersey', OK: 'Oklahoma', NM: 'New Mexico',
        KS: 'Kansas', MS: 'Mississippi', IA: 'Iowa', ND: 'North Dakota', SD: 'South Dakota',
        NE: 'Nebraska', WV: 'West Virginia', VT: 'Vermont', NH: 'New Hampshire', ID: 'Idaho',
        ME: 'Maine', RI: 'Rhode Island', CT: 'Connecticut', DE: 'Delaware', AK: 'Alaska',
        HI: 'Hawaii', DC: 'District of Columbia',
    };
    for (const e of REAL_MUGSHOT_ENTRIES) {
        if (!seen.has(e.jurisdictionId)) {
            seen.set(e.jurisdictionId, {
                jurisdictionId: e.jurisdictionId,
                displayName: e.countyDisplayName,
                stateCode: e.stateCode,
                stateName: stateNames[e.stateCode] || e.stateCode,
            });
        }
    }
    return Array.from(seen.values());
})();

/** Pull a real entry by personId (demo ID like REAL-0012) for lookup from the UI */
export function getRealEntryByPersonId(personId: string): RealMugshotEntry | undefined {
    // Strip duplication suffix (e.g. "REAL-0012-3" -> "REAL-0012")
    const base = personId.replace(/-\d+$/, '');
    return REAL_MUGSHOT_ENTRIES.find((e) => e.personId === base);
}
